title: Render Order 66
email: renderorder66@gmail.com
description: All things Gamedev
author: Anthony Reed & Corey Underdown
baseurl: ""
url: "https://renderorder66.com"
future: true

# Social Profiles
twitter_username:
github_username:
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-160303651-1 # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
